# Generated by Django 4.2.13 on 2024-07-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_label_note_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.label'),
        ),
    ]
