# Generated by Django 4.2.13 on 2024-07-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.label'),
        ),
    ]
