# Generated by Django 4.2.13 on 2024-08-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_note_trashed_alter_label_name_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='trash_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
