# Generated by Django 4.2.13 on 2024-08-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_trash_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='trash_at',
            new_name='trashed_at',
        ),
    ]
