# Generated by Django 4.2.13 on 2024-08-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_rename_trash_at_note_trashed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
