# Generated by Django 4.2.13 on 2024-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_note_trashed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='label',
        ),
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='labels', to='notes.label'),
        ),
    ]
